"""
IEEE case9-bus reference network builder (GENERATED — do not edit by hand).

Source: MATPOWER case9, accessed via ``pandapower.networks.case9`` (pandapower 3.4.0).
Generated by: ``scripts/generate_ieee_references.py``.

This is OUR copy of the network, translated faithfully from pandapower's
internal per-unit model. It is used for cross-validation of our Newton-Raphson
power flow against pandapower's independent implementation. Regenerate with::

    pip install pandapower==3.4.0
    poetry run python scripts/generate_ieee_references.py --confirm

Fidelity (this dict vs ``pandapower.networks.case9``): structurally identical (asserted at generation time).
"""

from __future__ import annotations

from typing import Any

_NETWORK: dict[str, Any] = {
    "header": {
        "name": "IEEE case9 (MATPOWER, via pandapower 3.4.0)",
        "revision": 0,
        "base_kv": 345.0,
        "base_mva": 100.0,
        "defaults": {"reference_tool": "pandapower 3.4.0", "reference_source": "MATPOWER case9"},
    },
    "buses": [
        {"ref_id": "B0", "id": "B0", "name": "B0", "u_n_kv": 345.0, "bus_kind": "slack"},
        {"ref_id": "B1", "id": "B1", "name": "B1", "u_n_kv": 345.0, "bus_kind": "pv"},
        {"ref_id": "B2", "id": "B2", "name": "B2", "u_n_kv": 345.0, "bus_kind": "pv"},
        {"ref_id": "B3", "id": "B3", "name": "B3", "u_n_kv": 345.0, "bus_kind": "pq"},
        {"ref_id": "B4", "id": "B4", "name": "B4", "u_n_kv": 345.0, "bus_kind": "pq"},
        {"ref_id": "B5", "id": "B5", "name": "B5", "u_n_kv": 345.0, "bus_kind": "pq"},
        {"ref_id": "B6", "id": "B6", "name": "B6", "u_n_kv": 345.0, "bus_kind": "pq"},
        {"ref_id": "B7", "id": "B7", "name": "B7", "u_n_kv": 345.0, "bus_kind": "pq"},
        {"ref_id": "B8", "id": "B8", "name": "B8", "u_n_kv": 345.0, "bus_kind": "pq"},
    ],
    "branches": [
        {
            "ref_id": "BR0",
            "id": "BR0",
            "name": "BR0",
            "branch_type": "LineBranch",
            "from_bus": "B0",
            "to_bus": "B3",
            "r_pu": 0.0,
            "x_pu": 0.0576,
            "b_pu": 0.0,
            "length_km": 1.0,
        },
        {
            "ref_id": "BR1",
            "id": "BR1",
            "name": "BR1",
            "branch_type": "LineBranch",
            "from_bus": "B3",
            "to_bus": "B4",
            "r_pu": 0.017,
            "x_pu": 0.092,
            "b_pu": 0.158,
            "length_km": 1.0,
        },
        {
            "ref_id": "BR2",
            "id": "BR2",
            "name": "BR2",
            "branch_type": "LineBranch",
            "from_bus": "B4",
            "to_bus": "B5",
            "r_pu": 0.039,
            "x_pu": 0.17,
            "b_pu": 0.358,
            "length_km": 1.0,
        },
        {
            "ref_id": "BR3",
            "id": "BR3",
            "name": "BR3",
            "branch_type": "LineBranch",
            "from_bus": "B2",
            "to_bus": "B5",
            "r_pu": 0.0,
            "x_pu": 0.0586,
            "b_pu": 0.0,
            "length_km": 1.0,
        },
        {
            "ref_id": "BR4",
            "id": "BR4",
            "name": "BR4",
            "branch_type": "LineBranch",
            "from_bus": "B5",
            "to_bus": "B6",
            "r_pu": 0.0119,
            "x_pu": 0.1008,
            "b_pu": 0.209,
            "length_km": 1.0,
        },
        {
            "ref_id": "BR5",
            "id": "BR5",
            "name": "BR5",
            "branch_type": "LineBranch",
            "from_bus": "B6",
            "to_bus": "B7",
            "r_pu": 0.0085,
            "x_pu": 0.072,
            "b_pu": 0.149,
            "length_km": 1.0,
        },
        {
            "ref_id": "BR6",
            "id": "BR6",
            "name": "BR6",
            "branch_type": "LineBranch",
            "from_bus": "B7",
            "to_bus": "B1",
            "r_pu": 0.0,
            "x_pu": 0.0625,
            "b_pu": 0.0,
            "length_km": 1.0,
        },
        {
            "ref_id": "BR7",
            "id": "BR7",
            "name": "BR7",
            "branch_type": "LineBranch",
            "from_bus": "B7",
            "to_bus": "B8",
            "r_pu": 0.032,
            "x_pu": 0.161,
            "b_pu": 0.306,
            "length_km": 1.0,
        },
        {
            "ref_id": "BR8",
            "id": "BR8",
            "name": "BR8",
            "branch_type": "LineBranch",
            "from_bus": "B8",
            "to_bus": "B3",
            "r_pu": 0.01,
            "x_pu": 0.085,
            "b_pu": 0.176,
            "length_km": 1.0,
        },
    ],
    "shunts": [],
    "transformers": [],
    "sources": [
        {
            "ref_id": "SLACK",
            "id": "SLACK",
            "name": "External grid (slack)",
            "bus": "B0",
            "v_pu": 1.0,
            "source_kind": "slack",
        }
    ],
    "generators": [
        {
            "ref_id": "GEN-1",
            "id": "GEN-1",
            "bus": "B1",
            "p_mw": 163.0,
            "v_pu": 1.0,
            "gen_kind": "pv",
        },
        {
            "ref_id": "GEN-2",
            "id": "GEN-2",
            "bus": "B2",
            "p_mw": 85.0,
            "v_pu": 1.0,
            "gen_kind": "pv",
        },
    ],
    "loads": [
        {"ref_id": "LOAD-0", "id": "LOAD-0", "bus": "B4", "p_mw": 90.0, "q_mvar": 30.0},
        {"ref_id": "LOAD-1", "id": "LOAD-1", "bus": "B6", "p_mw": 100.0, "q_mvar": 35.0},
        {"ref_id": "LOAD-2", "id": "LOAD-2", "bus": "B8", "p_mw": 125.0, "q_mvar": 50.0},
    ],
    "substations": [],
    "bays": [],
    "junctions": [],
    "corridors": [],
    "measurements": [],
    "protection_assignments": [],
}


def build_ieee_9bus_network() -> dict[str, Any]:
    """Return ENM-like dict representation of IEEE case9 (MATPOWER)."""
    import copy

    return copy.deepcopy(_NETWORK)
