import type { TechnicalIconName } from '../icons/technicalIconRegistry';
import type { AreaId } from '../navigation/areaRegistry';
import type {
  SurfaceSubjectKind,
  WorkspaceSurfaceKind,
  WorkspaceSurfaceSizeClass,
} from './types';

export type CanonScreenId =
  | 'E-00' | 'E-01' | 'E-02' | 'E-03' | 'E-04' | 'E-05' | 'E-06' | 'E-07' | 'E-08' | 'E-09'
  | 'E-10' | 'E-11' | 'E-12' | 'E-13' | 'E-14' | 'E-15' | 'E-16' | 'E-17' | 'E-18' | 'E-19'
  | 'E-20' | 'E-21' | 'E-22' | 'E-23' | 'E-24' | 'E-25' | 'E-26' | 'E-27' | 'E-28' | 'E-29'
  | 'E-30' | 'E-31' | 'E-32' | 'E-33' | 'E-34' | 'E-35' | 'E-36' | 'E-37' | 'E-38' | 'E-39';

export type CanonicalScreenCode = CanonScreenId;

export interface ScreenCanonDefinition {
  id: CanonScreenId;
  code: CanonScreenId;
  labelFull: string;
  labelShort: string;
  label: string;
  areaId: AreaId;
  area: AreaId;
  icon: TechnicalIconName;
  canonicalRoute: string;
  legacyAliases: string[];
  componentKey: string;
  componentRef: string;
  testId: string;
  implemented: boolean;
  requiresProject: boolean;
  requiresSelection: boolean;
  requiresStudyCase: boolean;
  requiresOperatingVariant: boolean;
  visibleInNavigation: boolean;
  surfaceKind: WorkspaceSurfaceKind;
  subjectKind: SurfaceSubjectKind;
  sizeClass: WorkspaceSurfaceSizeClass;
  supportsMiniSld: boolean;
  supportsChildren: boolean;
  requiresSession: boolean;
}

type ScreenInput = Omit<ScreenCanonDefinition, 'code' | 'label' | 'area' | 'componentRef'>;

function screen(definition: ScreenInput): ScreenCanonDefinition {
  return {
    ...definition,
    code: definition.id,
    label: definition.labelFull,
    area: definition.areaId,
    componentRef: definition.componentKey,
  };
}

export const SCREEN_CANON_REGISTRY: Readonly<Record<CanonScreenId, ScreenCanonDefinition>> = {
  'E-00': screen({
    id: 'E-00',
    labelFull: 'Pulpit projektu',
    labelShort: 'Pulpit',
    areaId: 'MODEL_SIECI',
    icon: 'ikona-ekran-pulpit-projektu',
    canonicalRoute: '/workspace/project',
    legacyAliases: ['project_dashboard', 'dashboard'],
    componentKey: 'ProjectDashboardSurface',
    testId: 'screen-E-00-project-dashboard',
    implemented: true,
    requiresProject: false,
    requiresSelection: false,
    requiresStudyCase: false,
    requiresOperatingVariant: false,
    visibleInNavigation: true,
    surfaceKind: 'pomocniczy',
    subjectKind: 'entity',
    sizeClass: 'C',
    supportsMiniSld: false,
    supportsChildren: true,
    requiresSession: false,
  }),
  'E-01': screen({
    id: 'E-01',
    labelFull: 'Główne środowisko pracy SLD',
    labelShort: 'Środowisko SLD',
    areaId: 'SCHEMAT_TOPOLOGIA',
    icon: 'ikona-ekran-sld',
    canonicalRoute: '/workspace/sld',
    legacyAliases: ['sld', 'sld-view', 'network_build'],
    componentKey: 'CanonicalLayout',
    testId: 'screen-E-01-sld-workspace',
    implemented: true,
    requiresProject: false,
    requiresSelection: false,
    requiresStudyCase: false,
    requiresOperatingVariant: false,
    visibleInNavigation: true,
    surfaceKind: 'obiektowy',
    subjectKind: 'entity',
    sizeClass: 'C',
    supportsMiniSld: true,
    supportsChildren: true,
    requiresSession: false,
  }),
  'E-02': screen({
    id: 'E-02',
    labelFull: 'Panel modelu sieci',
    labelShort: 'Model sieci',
    areaId: 'MODEL_SIECI',
    icon: 'ikona-ekran-panel-modelu',
    canonicalRoute: '/workspace/network-model',
    legacyAliases: ['network_tree', 'network-model-panel'],
    componentKey: 'NetworkTreeSurface',
    testId: 'screen-E-02-network-model-panel',
    implemented: true,
    requiresProject: true,
    requiresSelection: false,
    requiresStudyCase: false,
    requiresOperatingVariant: false,
    visibleInNavigation: true,
    surfaceKind: 'obiektowy',
    subjectKind: 'entity',
    sizeClass: 'B',
    supportsMiniSld: false,
    supportsChildren: false,
    requiresSession: false,
  }),
  'E-03': screen({
    id: 'E-03',
    labelFull: 'Inspektor techniczny',
    labelShort: 'Inspektor',
    areaId: 'MODEL_SIECI',
    icon: 'ikona-ekran-inspektor-techniczny',
    canonicalRoute: '/workspace/technical-inspector',
    legacyAliases: ['inspector', 'element_inspector', 'properties'],
    componentKey: 'ElementInspectorSurface',
    testId: 'screen-E-03-technical-inspector',
    implemented: true,
    requiresProject: true,
    requiresSelection: false,
    requiresStudyCase: false,
    requiresOperatingVariant: false,
    visibleInNavigation: true,
    surfaceKind: 'obiektowy',
    subjectKind: 'entity',
    sizeClass: 'B',
    supportsMiniSld: true,
    supportsChildren: true,
    requiresSession: false,
  }),
  'E-04': screen({
    id: 'E-04',
    labelFull: 'Gotowość modelu',
    labelShort: 'Gotowość',
    areaId: 'STUDIA_OBLICZENIOWE',
    icon: 'ikona-ekran-gotowosc-modelu',
    canonicalRoute: '/workspace/model-readiness',
    legacyAliases: ['model_gaps', 'readiness'],
    componentKey: 'ModelGapsSurface',
    testId: 'screen-E-04-model-readiness',
    implemented: true,
    requiresProject: true,
    requiresSelection: false,
    requiresStudyCase: true,
    requiresOperatingVariant: false,
    visibleInNavigation: true,
    surfaceKind: 'analityczny',
    subjectKind: 'analysis_case',
    sizeClass: 'B',
    supportsMiniSld: false,
    supportsChildren: false,
    requiresSession: true,
  }),
  'E-05': screen({
    id: 'E-05',
    labelFull: 'Menu obiektu na SLD',
    labelShort: 'Menu SLD',
    areaId: 'SCHEMAT_TOPOLOGIA',
    icon: 'ikona-ekran-menu-obiektu',
    canonicalRoute: '/workspace/sld-object-menu',
    legacyAliases: ['schematic_context_menu', 'context_menu'],
    componentKey: 'SchematicContextMenuSurface',
    testId: 'screen-E-05-sld-object-menu',
    implemented: true,
    requiresProject: true,
    requiresSelection: true,
    requiresStudyCase: false,
    requiresOperatingVariant: false,
    visibleInNavigation: false,
    surfaceKind: 'pomocniczy',
    subjectKind: 'entity',
    sizeClass: 'B',
    supportsMiniSld: true,
    supportsChildren: false,
    requiresSession: false,
  }),
  'E-06': screen({
    id: 'E-06',
    labelFull: 'Nakładki wynikowe SLD',
    labelShort: 'Nakładki SLD',
    areaId: 'WYNIKI_ANALIZY',
    icon: 'ikona-ekran-nakladki-wynikowe',
    canonicalRoute: '/workspace/sld-result-overlays',
    legacyAliases: ['analysis_overlay', 'result_overlay'],
    componentKey: 'AnalysisWorkspaceSurface',
    testId: 'screen-E-06-sld-result-overlays',
    implemented: true,
    requiresProject: true,
    requiresSelection: false,
    requiresStudyCase: true,
    requiresOperatingVariant: true,
    visibleInNavigation: true,
    surfaceKind: 'analityczny',
    subjectKind: 'analysis_run',
    sizeClass: 'C',
    supportsMiniSld: true,
    supportsChildren: true,
    requiresSession: true,
  }),
  'E-07': screen({
    id: 'E-07',
    labelFull: 'Zakresy obliczeń',
    labelShort: 'Zakresy',
    areaId: 'STUDIA_OBLICZENIOWE',
    icon: 'ikona-ekran-przypadki-obliczeniowe',
    canonicalRoute: '/workspace/study-cases',
    legacyAliases: ['case_context', 'analysis_cases'],
    componentKey: 'AnalysisCasesSurface',
    testId: 'screen-E-07-study-cases',
    implemented: true,
    requiresProject: true,
    requiresSelection: false,
    requiresStudyCase: false,
    requiresOperatingVariant: false,
    visibleInNavigation: true,
    surfaceKind: 'analityczny',
    subjectKind: 'analysis_case',
    sizeClass: 'B',
    supportsMiniSld: false,
    supportsChildren: false,
    requiresSession: true,
  }),
  'E-08': screen({
    id: 'E-08',
    labelFull: 'Warianty pracy',
    labelShort: 'Warianty',
    areaId: 'STUDIA_OBLICZENIOWE',
    icon: 'ikona-ekran-warianty-pracy',
    canonicalRoute: '/workspace/operating-variants',
    legacyAliases: ['variants', 'variants_runs', 'switching_variants'],
    componentKey: 'VariantSwitchingSurface',
    testId: 'screen-E-08-operating-variants',
    implemented: true,
    requiresProject: true,
    requiresSelection: false,
    requiresStudyCase: true,
    requiresOperatingVariant: false,
    visibleInNavigation: true,
    surfaceKind: 'analityczny',
    subjectKind: 'analysis_case',
    sizeClass: 'B',
    supportsMiniSld: true,
    supportsChildren: false,
    requiresSession: true,
  }),
  'E-09': screen({
    id: 'E-09',
    labelFull: 'Wersje modelu i historia obliczeń',
    labelShort: 'Wersje',
    areaId: 'HISTORIA_AUDYT',
    icon: 'ikona-ekran-migawki-historia',
    canonicalRoute: '/workspace/snapshots-and-runs',
    legacyAliases: ['run_history', 'snapshots'],
    componentKey: 'RunHistorySurface',
    testId: 'screen-E-09-snapshots-runs',
    implemented: true,
    requiresProject: true,
    requiresSelection: false,
    requiresStudyCase: true,
    requiresOperatingVariant: false,
    visibleInNavigation: true,
    surfaceKind: 'analityczny',
    subjectKind: 'analysis_run',
    sizeClass: 'B',
    supportsMiniSld: false,
    supportsChildren: false,
    requiresSession: true,
  }),
  'E-10': screen({
    id: 'E-10',
    labelFull: 'Główny Punkt Zasilający',
    labelShort: 'GPZ',
    areaId: 'MODEL_SIECI',
    icon: 'ikona-ekran-gpz',
    canonicalRoute: '/workspace/network/gpz',
    legacyAliases: ['gpz', 'source_supply', 'old:E-10'],
    componentKey: 'GpzSupplySourceSurface',
    testId: 'screen-E-10-gpz',
    implemented: true,
    requiresProject: true,
    requiresSelection: false,
    requiresStudyCase: false,
    requiresOperatingVariant: false,
    visibleInNavigation: true,
    surfaceKind: 'edycyjny',
    subjectKind: 'entity',
    sizeClass: 'B',
    supportsMiniSld: false,
    supportsChildren: true,
    requiresSession: true,
  }),
  'E-11': screen({
    id: 'E-11',
    labelFull: 'Pole SN',
    labelShort: 'Pole SN',
    areaId: 'MODEL_SIECI',
    icon: 'ikona-ekran-pole-sn',
    canonicalRoute: '/workspace/network/sn-bay',
    legacyAliases: ['sn_bay', 'field', 'old:E-14'],
    componentKey: 'FieldWorkspaceSurface',
    testId: 'screen-E-11-sn-bay',
    implemented: true,
    requiresProject: true,
    requiresSelection: true,
    requiresStudyCase: false,
    requiresOperatingVariant: false,
    visibleInNavigation: true,
    surfaceKind: 'edycyjny',
    subjectKind: 'entity',
    sizeClass: 'C',
    supportsMiniSld: true,
    supportsChildren: true,
    requiresSession: true,
  }),
  'E-12': screen({
    id: 'E-12',
    labelFull: 'Odcinek sieci SN',
    labelShort: 'Odcinek SN',
    areaId: 'MODEL_SIECI',
    icon: 'ikona-ekran-odcinek-sn',
    canonicalRoute: '/workspace/network/sn-segment',
    legacyAliases: ['segment', 'main_trunk_segment', 'old:E-11'],
    componentKey: 'MainTrunkSegmentSurface',
    testId: 'screen-E-12-sn-segment',
    implemented: true,
    requiresProject: true,
    requiresSelection: true,
    requiresStudyCase: false,
    requiresOperatingVariant: false,
    visibleInNavigation: true,
    surfaceKind: 'edycyjny',
    subjectKind: 'entity',
    sizeClass: 'A',
    supportsMiniSld: false,
    supportsChildren: true,
    requiresSession: true,
  }),
  'E-13': screen({
    id: 'E-13',
    labelFull: 'Stacja transformatorowa SN/nN',
    labelShort: 'Stacja SN/nN',
    areaId: 'MODEL_SIECI',
    icon: 'ikona-ekran-stacja-sn-nn',
    canonicalRoute: '/workspace/network/secondary-substation',
    legacyAliases: ['station', 'station_advanced', 'old:E-12', 'old:E-13'],
    componentKey: 'StationAdvancedSurface',
    testId: 'screen-E-13-secondary-substation',
    implemented: true,
    requiresProject: true,
    requiresSelection: true,
    requiresStudyCase: false,
    requiresOperatingVariant: false,
    visibleInNavigation: true,
    surfaceKind: 'edycyjny',
    subjectKind: 'entity',
    sizeClass: 'C',
    supportsMiniSld: true,
    supportsChildren: true,
    requiresSession: true,
  }),
  'E-14': screen({
    id: 'E-14',
    labelFull: 'Złącze kablowe SN',
    labelShort: 'ZKSN',
    areaId: 'MODEL_SIECI',
    icon: 'ikona-ekran-zksn',
    canonicalRoute: '/workspace/network/zksn',
    legacyAliases: ['zksn', 'old:E-19'],
    componentKey: 'ZksnSurface',
    testId: 'screen-E-14-zksn',
    implemented: true,
    requiresProject: true,
    requiresSelection: true,
    requiresStudyCase: false,
    requiresOperatingVariant: false,
    visibleInNavigation: true,
    surfaceKind: 'edycyjny',
    subjectKind: 'entity',
    sizeClass: 'B',
    supportsMiniSld: true,
    supportsChildren: true,
    requiresSession: true,
  }),
  'E-15': screen({
    id: 'E-15',
    labelFull: 'Słup rozgałęźny',
    labelShort: 'Słup rozg.',
    areaId: 'MODEL_SIECI',
    icon: 'ikona-ekran-slup-rozgalezny',
    canonicalRoute: '/workspace/network/branch-pole',
    legacyAliases: ['branch_pole', 'old:E-20'],
    componentKey: 'BranchPoleSurface',
    testId: 'screen-E-15-branch-pole',
    implemented: true,
    requiresProject: true,
    requiresSelection: true,
    requiresStudyCase: false,
    requiresOperatingVariant: false,
    visibleInNavigation: true,
    surfaceKind: 'edycyjny',
    subjectKind: 'entity',
    sizeClass: 'B',
    supportsMiniSld: false,
    supportsChildren: true,
    requiresSession: true,
  }),
  'E-16': screen({
    id: 'E-16',
    labelFull: 'Odgałęzienie',
    labelShort: 'Odgałęzienie',
    areaId: 'MODEL_SIECI',
    icon: 'ikona-ekran-odgalezienie',
    canonicalRoute: '/workspace/network/branch',
    legacyAliases: ['branch', 'old:E-21'],
    componentKey: 'BranchSurface',
    testId: 'screen-E-16-branch',
    implemented: true,
    requiresProject: true,
    requiresSelection: true,
    requiresStudyCase: false,
    requiresOperatingVariant: false,
    visibleInNavigation: true,
    surfaceKind: 'edycyjny',
    subjectKind: 'entity',
    sizeClass: 'A',
    supportsMiniSld: false,
    supportsChildren: false,
    requiresSession: true,
  }),
  'E-17': screen({
    id: 'E-17',
    labelFull: 'Punkt normalnie otwarty',
    labelShort: 'NOP',
    areaId: 'SCHEMAT_TOPOLOGIA',
    icon: 'ikona-ekran-punkt-normalnie-otwarty',
    canonicalRoute: '/workspace/topology/nop',
    legacyAliases: ['nop', 'ring_nop', 'old:E-22'],
    componentKey: 'RingNopSurface',
    testId: 'screen-E-17-nop',
    implemented: true,
    requiresProject: true,
    requiresSelection: true,
    requiresStudyCase: true,
    requiresOperatingVariant: true,
    visibleInNavigation: true,
    surfaceKind: 'edycyjny',
    subjectKind: 'entity',
    sizeClass: 'B',
    supportsMiniSld: false,
    supportsChildren: true,
    requiresSession: true,
  }),
  'E-18': screen({
    id: 'E-18',
    labelFull: 'Transformator SN/nN',
    labelShort: 'Transformator',
    areaId: 'MODEL_SIECI',
    icon: 'ikona-ekran-transformator',
    canonicalRoute: '/workspace/network/transformer',
    legacyAliases: ['transformer', 'old:E-15'],
    componentKey: 'TransformerSurface',
    testId: 'screen-E-18-transformer',
    implemented: true,
    requiresProject: true,
    requiresSelection: true,
    requiresStudyCase: false,
    requiresOperatingVariant: false,
    visibleInNavigation: true,
    surfaceKind: 'edycyjny',
    subjectKind: 'entity',
    sizeClass: 'B',
    supportsMiniSld: true,
    supportsChildren: true,
    requiresSession: true,
  }),
  'E-19': screen({
    id: 'E-19',
    labelFull: 'Strona nN stacji',
    labelShort: 'Strona nN',
    areaId: 'MODEL_SIECI',
    icon: 'ikona-ekran-strona-nn',
    canonicalRoute: '/workspace/network/lv-side',
    legacyAliases: ['station_lv_side', 'old:E-16'],
    componentKey: 'StationLvSideSurface',
    testId: 'screen-E-19-lv-side',
    implemented: true,
    requiresProject: true,
    requiresSelection: true,
    requiresStudyCase: false,
    requiresOperatingVariant: false,
    visibleInNavigation: true,
    surfaceKind: 'edycyjny',
    subjectKind: 'entity',
    sizeClass: 'B',
    supportsMiniSld: false,
    supportsChildren: true,
    requiresSession: true,
  }),
  'E-20': screen({
    id: 'E-20',
    labelFull: 'Obciążenie nN',
    labelShort: 'Obciążenie',
    areaId: 'MODEL_SIECI',
    icon: 'ikona-ekran-obciazenie-nn',
    canonicalRoute: '/workspace/network/lv-load',
    legacyAliases: ['nn_load', 'load', 'old:E-23'],
    componentKey: 'NnLoadSurface',
    testId: 'screen-E-20-lv-load',
    implemented: true,
    requiresProject: true,
    requiresSelection: true,
    requiresStudyCase: false,
    requiresOperatingVariant: false,
    visibleInNavigation: true,
    surfaceKind: 'edycyjny',
    subjectKind: 'entity',
    sizeClass: 'B',
    supportsMiniSld: false,
    supportsChildren: false,
    requiresSession: true,
  }),
  'E-21': screen({
    id: 'E-21',
    labelFull: 'Źródło fotowoltaiczne',
    labelShort: 'PV',
    areaId: 'ZRODLA_PRZYLACZENIA',
    icon: 'ikona-ekran-zrodlo-pv',
    canonicalRoute: '/workspace/sources/pv',
    legacyAliases: ['pv_source', 'old:E-17'],
    componentKey: 'PvSourceSurface',
    testId: 'screen-E-21-pv-source',
    implemented: true,
    requiresProject: true,
    requiresSelection: true,
    requiresStudyCase: false,
    requiresOperatingVariant: false,
    visibleInNavigation: true,
    surfaceKind: 'edycyjny',
    subjectKind: 'entity',
    sizeClass: 'B',
    supportsMiniSld: false,
    supportsChildren: true,
    requiresSession: true,
  }),
  'E-22': screen({
    id: 'E-22',
    labelFull: 'Magazyn energii',
    labelShort: 'BESS',
    areaId: 'ZRODLA_PRZYLACZENIA',
    icon: 'ikona-ekran-magazyn-energii',
    canonicalRoute: '/workspace/sources/bess',
    legacyAliases: ['bess_source', 'old:E-18'],
    componentKey: 'BessSourceSurface',
    testId: 'screen-E-22-bess-source',
    implemented: true,
    requiresProject: true,
    requiresSelection: true,
    requiresStudyCase: false,
    requiresOperatingVariant: false,
    visibleInNavigation: true,
    surfaceKind: 'edycyjny',
    subjectKind: 'entity',
    sizeClass: 'B',
    supportsMiniSld: false,
    supportsChildren: true,
    requiresSession: true,
  }),
  'E-23': screen({
    id: 'E-23',
    labelFull: 'Farma wiatrowa',
    labelShort: 'Farma wiatrowa',
    areaId: 'ZRODLA_PRZYLACZENIA',
    icon: 'ikona-ekran-farma-wiatrowa',
    canonicalRoute: '/workspace/sources/wind-farm',
    legacyAliases: ['fw_source', 'wind_farm'],
    componentKey: 'WindFarmSourceSurface',
    testId: 'screen-E-23-wind-farm',
    implemented: true,
    requiresProject: true,
    requiresSelection: true,
    requiresStudyCase: false,
    requiresOperatingVariant: false,
    visibleInNavigation: true,
    surfaceKind: 'edycyjny',
    subjectKind: 'entity',
    sizeClass: 'B',
    supportsMiniSld: false,
    supportsChildren: true,
    requiresSession: true,
  }),
  'E-24': screen({
    id: 'E-24',
    labelFull: 'Profile operatora i źródeł',
    labelShort: 'Profile',
    areaId: 'ZRODLA_PRZYLACZENIA',
    icon: 'ikona-ekran-profile',
    canonicalRoute: '/workspace/sources/profiles',
    legacyAliases: ['source_profiles', 'element_parameters', 'old:E-24'],
    componentKey: 'SourceProfilesSurface',
    testId: 'screen-E-24-source-profiles',
    implemented: true,
    requiresProject: true,
    requiresSelection: false,
    requiresStudyCase: false,
    requiresOperatingVariant: false,
    visibleInNavigation: true,
    surfaceKind: 'edycyjny',
    subjectKind: 'entity',
    sizeClass: 'B',
    supportsMiniSld: true,
    supportsChildren: false,
    requiresSession: true,
  }),
  'E-25': screen({
    id: 'E-25',
    labelFull: 'Charakterystyki regulacyjne',
    labelShort: 'Q(U), cos φ(P)',
    areaId: 'ZRODLA_PRZYLACZENIA',
    icon: 'ikona-ekran-charakterystyki-regulacyjne',
    canonicalRoute: '/workspace/sources/regulation-curves',
    legacyAliases: ['regulation_curves', 'old:E-25'],
    componentKey: 'RegulationCurvesSurface',
    testId: 'screen-E-25-regulation-curves',
    implemented: true,
    requiresProject: true,
    requiresSelection: false,
    requiresStudyCase: false,
    requiresOperatingVariant: false,
    visibleInNavigation: true,
    surfaceKind: 'edycyjny',
    subjectKind: 'entity',
    sizeClass: 'B',
    supportsMiniSld: false,
    supportsChildren: false,
    requiresSession: true,
  }),
  'E-26': screen({
    id: 'E-26',
    labelFull: 'Charakterystyki FRT/LVRT/HVRT',
    labelShort: 'FRT/LVRT/HVRT',
    areaId: 'ZRODLA_PRZYLACZENIA',
    icon: 'ikona-ekran-frt-lvrt-hvrt',
    canonicalRoute: '/workspace/sources/frt-lvrt-hvrt',
    legacyAliases: ['frt', 'source_compliance', 'catalog_admin', 'old:E-30'],
    componentKey: 'ComplianceSurface',
    testId: 'screen-E-26-frt-lvrt-hvrt',
    implemented: true,
    requiresProject: true,
    requiresSelection: false,
    requiresStudyCase: true,
    requiresOperatingVariant: true,
    visibleInNavigation: true,
    surfaceKind: 'analityczny',
    subjectKind: 'analysis_run',
    sizeClass: 'C',
    supportsMiniSld: true,
    supportsChildren: false,
    requiresSession: true,
  }),
  'E-27': screen({
    id: 'E-27',
    labelFull: 'Zabezpieczenia i automatyka',
    labelShort: 'Zabezpieczenia',
    areaId: 'ZABEZPIECZENIA_AUTOMATYKA',
    icon: 'ikona-ekran-zabezpieczenia-automatyka',
    canonicalRoute: '/workspace/protection-automation',
    legacyAliases: ['protection_automation'],
    componentKey: 'ProtectionAutomationSurface',
    testId: 'screen-E-27-protection-automation',
    implemented: true,
    requiresProject: true,
    requiresSelection: false,
    requiresStudyCase: true,
    requiresOperatingVariant: true,
    visibleInNavigation: true,
    surfaceKind: 'analityczny',
    subjectKind: 'analysis_run',
    sizeClass: 'C',
    supportsMiniSld: true,
    supportsChildren: false,
    requiresSession: true,
  }),
  'E-28': screen({
    id: 'E-28',
    labelFull: 'Koordynacja zabezpieczeń',
    labelShort: 'Koordynacja',
    areaId: 'ZABEZPIECZENIA_AUTOMATYKA',
    icon: 'ikona-ekran-koordynacja-zabezpieczen',
    canonicalRoute: '/workspace/protection-coordination',
    legacyAliases: ['protection_coordination', 'old:E-28'],
    componentKey: 'ProtectionCoordinationSurface',
    testId: 'screen-E-28-protection-coordination',
    implemented: true,
    requiresProject: true,
    requiresSelection: false,
    requiresStudyCase: true,
    requiresOperatingVariant: true,
    visibleInNavigation: true,
    surfaceKind: 'analityczny',
    subjectKind: 'analysis_run',
    sizeClass: 'C',
    supportsMiniSld: true,
    supportsChildren: false,
    requiresSession: true,
  }),
  'E-29': screen({
    id: 'E-29',
    labelFull: 'Sieć zerowa i składowe symetryczne',
    labelShort: 'Sieć zerowa',
    areaId: 'WYNIKI_ANALIZY',
    icon: 'ikona-ekran-siec-zerowa',
    canonicalRoute: '/workspace/results/zero-sequence',
    legacyAliases: ['symmetrical_components', 'zero_sequence', 'old:E-29'],
    componentKey: 'SymmetricalComponentsSurface',
    testId: 'screen-E-29-zero-sequence',
    implemented: true,
    requiresProject: true,
    requiresSelection: false,
    requiresStudyCase: true,
    requiresOperatingVariant: true,
    visibleInNavigation: true,
    surfaceKind: 'analityczny',
    subjectKind: 'analysis_run',
    sizeClass: 'C',
    supportsMiniSld: true,
    supportsChildren: false,
    requiresSession: true,
  }),
  'E-30': screen({
    id: 'E-30',
    labelFull: 'Rozpływ mocy',
    labelShort: 'Rozpływ',
    areaId: 'WYNIKI_ANALIZY',
    icon: 'ikona-ekran-rozplyw-mocy',
    canonicalRoute: '/workspace/results/load-flow',
    legacyAliases: ['load_flow', 'power_flow', 'convergence', 'old:E-34'],
    componentKey: 'ConvergenceOltcSurface',
    testId: 'screen-E-30-load-flow',
    implemented: true,
    requiresProject: true,
    requiresSelection: false,
    requiresStudyCase: true,
    requiresOperatingVariant: true,
    visibleInNavigation: true,
    surfaceKind: 'analityczny',
    subjectKind: 'analysis_run',
    sizeClass: 'B',
    supportsMiniSld: true,
    supportsChildren: false,
    requiresSession: true,
  }),
  'E-31': screen({
    id: 'E-31',
    labelFull: 'Stan fazowy SN',
    labelShort: 'Stan fazowy',
    areaId: 'WYNIKI_ANALIZY',
    icon: 'ikona-ekran-stan-fazowy',
    canonicalRoute: '/workspace/results/phase-state-sn',
    legacyAliases: ['phase_state_sn', 'assumptions_quality', 'old:E-31'],
    componentKey: 'AssumptionsQualitySurface',
    testId: 'screen-E-31-phase-state-sn',
    implemented: true,
    requiresProject: true,
    requiresSelection: false,
    requiresStudyCase: true,
    requiresOperatingVariant: true,
    visibleInNavigation: true,
    surfaceKind: 'analityczny',
    subjectKind: 'analysis_run',
    sizeClass: 'B',
    supportsMiniSld: false,
    supportsChildren: false,
    requiresSession: true,
  }),
  'E-32': screen({
    id: 'E-32',
    labelFull: 'Stabilność dynamiczna',
    labelShort: 'Stabilność',
    areaId: 'WYNIKI_ANALIZY',
    icon: 'ikona-ekran-stabilnosc-dynamiczna',
    canonicalRoute: '/workspace/results/dynamic-stability',
    legacyAliases: ['dynamic_stability'],
    componentKey: 'DynamicStabilitySurface',
    testId: 'screen-E-32-dynamic-stability',
    implemented: true,
    requiresProject: true,
    requiresSelection: false,
    requiresStudyCase: true,
    requiresOperatingVariant: true,
    visibleInNavigation: true,
    surfaceKind: 'analityczny',
    subjectKind: 'analysis_run',
    sizeClass: 'C',
    supportsMiniSld: true,
    supportsChildren: false,
    requiresSession: true,
  }),
  'E-33': screen({
    id: 'E-33',
    labelFull: 'Wkłady źródeł',
    labelShort: 'Wkłady',
    areaId: 'WYNIKI_ANALIZY',
    icon: 'ikona-ekran-wklady-zrodel',
    canonicalRoute: '/workspace/results/source-contributions',
    legacyAliases: ['source_contributions', 'old:E-32'],
    componentKey: 'SourceContributionsSurface',
    testId: 'screen-E-33-source-contributions',
    implemented: true,
    requiresProject: true,
    requiresSelection: false,
    requiresStudyCase: true,
    requiresOperatingVariant: true,
    visibleInNavigation: true,
    surfaceKind: 'analityczny',
    subjectKind: 'analysis_run',
    sizeClass: 'C',
    supportsMiniSld: true,
    supportsChildren: false,
    requiresSession: true,
  }),
  'E-34': screen({
    id: 'E-34',
    labelFull: 'Weryfikacja cieplna i dynamiczna',
    labelShort: 'I²t i dynamika',
    areaId: 'WYNIKI_ANALIZY',
    icon: 'ikona-ekran-weryfikacja-cieplna-dynamiczna',
    canonicalRoute: '/workspace/results/thermal-dynamic',
    legacyAliases: ['thermal_dynamic', 'old:E-33'],
    componentKey: 'ThermalDynamicSurface',
    testId: 'screen-E-34-thermal-dynamic',
    implemented: true,
    requiresProject: true,
    requiresSelection: false,
    requiresStudyCase: true,
    requiresOperatingVariant: true,
    visibleInNavigation: true,
    surfaceKind: 'analityczny',
    subjectKind: 'analysis_run',
    sizeClass: 'C',
    supportsMiniSld: true,
    supportsChildren: false,
    requiresSession: true,
  }),
  'E-35': screen({
    id: 'E-35',
    labelFull: 'Wyniki i porównania',
    labelShort: 'Wyniki',
    areaId: 'WYNIKI_ANALIZY',
    icon: 'ikona-ekran-wyniki-porownania',
    canonicalRoute: '/workspace/results',
    legacyAliases: ['analysis', 'results', 'old:E-06'],
    componentKey: 'AnalysisWorkspaceSurface',
    testId: 'screen-E-35-results-comparison',
    implemented: true,
    requiresProject: true,
    requiresSelection: false,
    requiresStudyCase: true,
    requiresOperatingVariant: true,
    visibleInNavigation: true,
    surfaceKind: 'analityczny',
    subjectKind: 'analysis_run',
    sizeClass: 'C',
    supportsMiniSld: true,
    supportsChildren: true,
    requiresSession: true,
  }),
  'E-36': screen({
    id: 'E-36',
    labelFull: 'Uzasadnienie inżynierskie',
    labelShort: 'Uzasadnienie',
    areaId: 'RAPORTY_UZASADNIENIA',
    icon: 'ikona-ekran-uzasadnienie',
    canonicalRoute: '/workspace/proof',
    legacyAliases: ['proof', 'proof_pack'],
    componentKey: 'ProofSurface',
    testId: 'screen-E-36-proof',
    implemented: true,
    requiresProject: true,
    requiresSelection: false,
    requiresStudyCase: true,
    requiresOperatingVariant: true,
    visibleInNavigation: true,
    surfaceKind: 'raportowy',
    subjectKind: 'proof_pack',
    sizeClass: 'C',
    supportsMiniSld: true,
    supportsChildren: true,
    requiresSession: true,
  }),
  'E-37': screen({
    id: 'E-37',
    labelFull: 'Raporty OSD i audytowe',
    labelShort: 'Raporty',
    areaId: 'RAPORTY_UZASADNIENIA',
    icon: 'ikona-ekran-raporty-osd-audytowe',
    canonicalRoute: '/workspace/reports',
    legacyAliases: ['report', 'report_workspace', 'old:E-27'],
    componentKey: 'ReportWorkspaceSurface',
    testId: 'screen-E-37-reports',
    implemented: true,
    requiresProject: true,
    requiresSelection: false,
    requiresStudyCase: true,
    requiresOperatingVariant: true,
    visibleInNavigation: true,
    surfaceKind: 'raportowy',
    subjectKind: 'report',
    sizeClass: 'C',
    supportsMiniSld: true,
    supportsChildren: true,
    requiresSession: true,
  }),
  'E-38': screen({
    id: 'E-38',
    labelFull: 'Katalogi techniczne',
    labelShort: 'Katalogi',
    areaId: 'KATALOGI_TECHNICZNE',
    icon: 'ikona-ekran-katalogi-techniczne',
    canonicalRoute: '/workspace/catalogs',
    legacyAliases: ['catalog_admin', 'catalog', 'old:E-26'],
    componentKey: 'CatalogAdminSurface',
    testId: 'screen-E-38-catalogs',
    implemented: true,
    requiresProject: false,
    requiresSelection: false,
    requiresStudyCase: false,
    requiresOperatingVariant: false,
    visibleInNavigation: true,
    surfaceKind: 'pomocniczy',
    subjectKind: 'helper_context',
    sizeClass: 'B',
    supportsMiniSld: false,
    supportsChildren: false,
    requiresSession: true,
  }),
  'E-39': screen({
    id: 'E-39',
    labelFull: 'Historia i audyt',
    labelShort: 'Historia',
    areaId: 'HISTORIA_AUDYT',
    icon: 'ikona-ekran-historia-audyt',
    canonicalRoute: '/workspace/audit-history',
    legacyAliases: ['history', 'audit', 'run_history'],
    componentKey: 'RunHistorySurface',
    testId: 'screen-E-39-audit-history',
    implemented: true,
    requiresProject: true,
    requiresSelection: false,
    requiresStudyCase: false,
    requiresOperatingVariant: false,
    visibleInNavigation: true,
    surfaceKind: 'analityczny',
    subjectKind: 'analysis_run',
    sizeClass: 'B',
    supportsMiniSld: false,
    supportsChildren: false,
    requiresSession: true,
  }),
};

export const CANONICAL_SCREEN_REGISTRY = SCREEN_CANON_REGISTRY;

export const CANONICAL_SCREEN_CODES = Object.keys(SCREEN_CANON_REGISTRY) as CanonScreenId[];

export function getScreenDefinition(screenId: CanonScreenId): ScreenCanonDefinition {
  return SCREEN_CANON_REGISTRY[screenId];
}

export function isCanonScreenId(value: unknown): value is CanonScreenId {
  return typeof value === 'string' && value in SCREEN_CANON_REGISTRY;
}

export function resolveLegacyScreenAlias(alias: string | null | undefined): ScreenCanonDefinition | null {
  if (!alias) {
    return null;
  }
  if (isCanonScreenId(alias)) {
    return getScreenDefinition(alias);
  }
  const normalized = alias.trim();
  return (
    CANONICAL_SCREEN_CODES
      .map((screenId) => getScreenDefinition(screenId))
      .find((definition) => definition.legacyAliases.includes(normalized)) ?? null
  );
}

export function resolveScreenByRoute(route: string | null | undefined): ScreenCanonDefinition | null {
  if (!route) {
    return null;
  }
  const normalized = route.trim();
  return (
    CANONICAL_SCREEN_CODES
      .map((screenId) => getScreenDefinition(screenId))
      .find((definition) => definition.canonicalRoute === normalized) ?? null
  );
}

export function getScreensByArea(areaId: AreaId): ScreenCanonDefinition[] {
  return CANONICAL_SCREEN_CODES
    .map((screenId) => getScreenDefinition(screenId))
    .filter((definition) => definition.areaId === areaId);
}
