/* Stringi PL warsztatu przestrzeni „Wyniki" (scalenie U3 #1). */

export const WYNIKI_WARSZTAT_STRINGS = {
  ariaZakladki: 'Widoki wyników',
  grupaAnalizy: 'Analizy sieci',
  grupaOze: 'OZE i przyłączenia',
  zakladkaWerdykt: 'Werdykt projektowy',
  zakladkaCoWymagaUwagi: 'Co wymaga uwagi',
  zakladkaRozplyw: 'Rozpływ mocy',
  zakladkaRegulacjaOltc: 'Regulacja OLTC',
  zakladkaZbieznosc: 'Zbieżność rozpływu',
  zakladkaZwarcia: 'Zwarcia',
  zakladkaKoordynacja: 'Koordynacja zabezpieczeń',
  zakladkaSkladowe: 'Składowe symetryczne',
  zakladkaDowod: 'Dowód obliczeń',
  zakladkaStanFazowy: 'Stan fazowy SN',
  zakladkaStabilnosc: 'Stabilność dynamiczna',
  zakladkaNcRfg: 'Zgodność NC RfG',
  zakladkaPulpitOze: 'Pulpit OZE',
  zakladkaJakosc: 'Jakość wyników',
  zakladkaZdolnosc: 'Zdolność przyłączeniowa',
  zakladkaRanking: 'Ranking przyłączeń',
  zakladkaKrzywe: 'Krzywe P–Q',
  zakladkaObszar: 'Obszar pracy P–Q',
  zakladkaStudium: 'Studium przyłączenia',
  zakladkaFrt: 'Walidacja falownika',
  zakladkaOsd: 'Polecenia OSD',
  zakladkaKompensacja: 'Dobór kompensacji',
  zakladkaLom: 'Praca wyspowa',
  zakladkaWniosek: 'Wniosek OSD',
  zakladkaPorownanie: 'Porównanie A/B',
  zakladkaOdbior: 'Zgodność powykonawcza',
  zakladkaEstymacja: 'Estymacja stanu',
  zakladkaSsci: 'Stabilność SSCI',
  porownanieBezProjektu: 'Otwórz projekt, aby porównywać przebiegi obliczeń.',
  zakladkaPozostale: 'Pozostałe analizy',
  dowodBezPrzebiegu: 'Analiza',
} as const;
