/* Stringi PL warsztatu przestrzeni „Wyniki" (scalenie U3 #1; nawigacja
 * obszar → analiza wg karty B-02 / W3-E). */

export const WYNIKI_WARSZTAT_STRINGS = {
  ariaObszary: 'Obszary wyników',
  ariaZakladki: 'Analizy obszaru',
  obszarOcena: 'Ocena i przegląd',
  obszarRozplyw: 'Rozpływ mocy i napięcia',
  obszarZwarcia: 'Zwarcia i zabezpieczenia',
  obszarStabilnosc: 'Stabilność i przekształtniki',
  obszarSpecjalistyczne: 'Analizy specjalistyczne',
  obszarOze: 'OZE i przyłączenia',
  obszarKlasyczne: 'Widoki klasyczne',
  zakladkaOcena: 'Ocena techniczna wyników',
  zakladkaCoWymagaUwagi: 'Co wymaga uwagi',
  zakladkaRozplyw: 'Rozpływ mocy',
  zakladkaRegulacjaOltc: 'Regulacja OLTC',
  zakladkaZbieznosc: 'Zbieżność rozpływu',
  zakladkaKontyngencje: 'Kontyngencje N-1',
  zakladkaZwarcia: 'Zwarcia',
  zakladkaKoordynacja: 'Koordynacja zabezpieczeń',
  zakladkaSkladowe: 'Składowe symetryczne',
  zakladkaDowod: 'Dowód obliczeń',
  zakladkaStanFazowy: 'Stan fazowy SN',
  zakladkaStabilnosc: 'Stabilność dynamiczna',
  zakladkaNcRfg: 'Zgodność NC RfG',
  zakladkaPulpitOze: 'Pulpit OZE',
  zakladkaJakosc: 'Jakość wyników',
  zakladkaWrazliwosc: 'Wrażliwość',
  zakladkaZdolnosc: 'Zdolność przyłączeniowa',
  zakladkaRanking: 'Ranking przyłączeń',
  zakladkaKrzywe: 'Krzywe P–Q',
  zakladkaObszar: 'Obszar pracy P–Q',
  zakladkaStudium: 'Studium przyłączenia',
  zakladkaFrt: 'Walidacja falownika',
  zakladkaOsd: 'Polecenia OSD',
  zakladkaKompensacja: 'Dobór kompensacji',
  zakladkaLom: 'Praca wyspowa',
  zakladkaWniosek: 'Wniosek OSD',
  zakladkaPorownanie: 'Porównanie A/B',
  zakladkaOdbior: 'Zgodność powykonawcza',
  zakladkaEstymacja: 'Estymacja stanu',
  zakladkaSsci: 'Stabilność SSCI',
  zakladkaAkademickie: 'Analizy specjalistyczne',
  porownanieBezProjektu: 'Otwórz projekt, aby porównywać przebiegi obliczeń.',
  zakladkaPozostale: 'Widoki klasyczne',
  dowodBezPrzebiegu: 'Analiza',
} as const;
