import type { CanonicalOpName } from '../../../types/domainOps';
import type {
  WorkspaceOpenMode,
  WorkspaceScreenCode,
  WorkspaceSurfaceSaveMode,
  WorkspaceSurfaceSizeClass,
} from '../../workspace/types';

export interface OperationSurfaceEntry {
  canonicalOp: CanonicalOpName;
  componentName: string;
  labelPl: string;
  implemented: boolean;
  screenCode: WorkspaceScreenCode;
  sizeClass: WorkspaceSurfaceSizeClass;
  saveMode: WorkspaceSurfaceSaveMode;
  openMode: WorkspaceOpenMode;
  supportsMiniSld: boolean;
  defaultTab: string | null;
}

function entry(
  canonicalOp: CanonicalOpName,
  componentName: string,
  labelPl: string,
  screenCode: WorkspaceScreenCode,
  sizeClass: WorkspaceSurfaceSizeClass,
  saveMode: WorkspaceSurfaceSaveMode,
  openMode: WorkspaceOpenMode,
  supportsMiniSld: boolean,
  defaultTab: string | null,
): OperationSurfaceEntry {
  return {
    canonicalOp,
    componentName,
    labelPl,
    implemented: true,
    screenCode,
    sizeClass,
    saveMode,
    openMode,
    supportsMiniSld,
    defaultTab,
  };
}

export const OPERATION_SURFACE_REGISTRY: readonly OperationSurfaceEntry[] = [
  entry(
    'continue_trunk_segment_sn',
    'ContinueTrunkForm',
    'Kontynuuj ciag glowny SN',
    'E-11',
    'A',
    'manual',
    'replace_right_panel',
    false,
    'kabel-sn',
  ),
  entry(
    'insert_station_on_segment_sn',
    'InsertStationForm',
    'Wstaw stacje SN/nN',
    'E-12',
    'B',
    'manual',
    'replace_right_panel',
    true,
    'typ-topologiczny',
  ),
  entry(
    'start_branch_segment_sn',
    'StartBranchForm',
    'Dodaj odgalezienie SN',
    'E-21',
    'A',
    'manual',
    'replace_right_panel',
    false,
    'rodzina-odgalezienia',
  ),
  entry(
    'insert_section_switch_sn',
    'InsertSectionSwitchForm',
    'Wstaw lacznik sekcyjny',
    'E-22',
    'B',
    'manual',
    'replace_right_panel',
    true,
    'domkniecie-pierscienia',
  ),
  entry(
    'connect_secondary_ring_sn',
    'ConnectRingForm',
    'Domknij pierscien wtorny',
    'E-22',
    'B',
    'manual',
    'replace_right_panel',
    true,
    'domkniecie-pierscienia',
  ),
  entry(
    'set_normal_open_point',
    'ConnectRingForm',
    'Ustaw punkt normalnie otwarty',
    'E-22',
    'B',
    'auto',
    'replace_right_panel',
    true,
    'punkt-normalnie-otwarty',
  ),
  entry(
    'add_nn_outgoing_field',
    'AddNnOutgoingFieldForm',
    'Dodaj odplyw nN',
    'E-16',
    'A',
    'manual',
    'replace_right_panel',
    false,
    'odplywy',
  ),
  entry(
    'add_nn_load',
    'AddNnLoadForm',
    'Dodaj obciazenie nN',
    'E-23',
    'A',
    'manual',
    'replace_right_panel',
    false,
    'obciazenie',
  ),
  entry(
    'add_converter_source',
    'AddConverterSourceForm',
    'Dodaj zrodlo przeksztaltnikowe',
    'E-17',
    'B',
    'manual',
    'replace_right_panel',
    true,
    'identyfikacja',
  ),
  entry(
    'add_relay',
    'AddRelayForm',
    'Dodaj zabezpieczenie',
    'E-14',
    'B',
    'manual',
    'replace_right_panel',
    true,
    'zabezpieczenia',
  ),
  entry(
    'assign_catalog_to_element',
    'AssignCatalogForm',
    'Przypisz katalog do elementu',
    'E-26',
    'A',
    'manual',
    'replace_right_panel',
    false,
    'katalogi',
  ),
  entry(
    'update_element_parameters',
    'UpdateElementParametersForm',
    'Zmien parametry elementu',
    'E-24',
    'B',
    'manual',
    'replace_right_panel',
    true,
    'parametry',
  ),
  entry(
    'add_genset_nn',
    'AddDispatchableSourceForm',
    'Dodaj agregat nN',
    'E-16',
    'B',
    'manual',
    'replace_right_panel',
    false,
    'zrodla',
  ),
  entry(
    'add_ups_nn',
    'AddDispatchableSourceForm',
    'Dodaj UPS nN',
    'E-16',
    'B',
    'manual',
    'replace_right_panel',
    false,
    'zrodla',
  ),
  entry(
    'add_grid_source_sn',
    'AddGridSourceForm',
    'Dodaj zrodlo zasilania GPZ',
    'E-10',
    'B',
    'manual',
    'replace_right_panel',
    false,
    'uproszczony',
  ),
  entry(
    'add_sn_bay',
    'AddSnBayForm',
    'Dodaj pole SN',
    'E-14',
    'B',
    'manual',
    'replace_right_panel',
    true,
    'identyfikacja',
  ),
  entry(
    'add_transformer_sn_nn',
    'AddTransformerForm',
    'Dodaj transformator SN/nN',
    'E-15',
    'B',
    'manual',
    'replace_right_panel',
    true,
    'transformator',
  ),
  entry(
    'insert_branch_pole_on_segment_sn',
    'InsertBranchPoleForm',
    'Wstaw slup rozgalezny',
    'E-20',
    'B',
    'manual',
    'replace_right_panel',
    true,
    'identyfikacja',
  ),
  entry(
    'insert_zksn_on_segment_sn',
    'InsertZksnForm',
    'Wstaw zlacze kablowe SN',
    'E-19',
    'B',
    'transactional',
    'replace_right_panel',
    true,
    'identyfikacja',
  ),
  entry(
    'add_ct',
    'AddMeasurementForm',
    'Dodaj przekladnik pradowy',
    'E-14',
    'B',
    'manual',
    'replace_right_panel',
    true,
    'przekladniki',
  ),
  entry(
    'add_vt',
    'AddMeasurementForm',
    'Dodaj przekladnik napieciowy',
    'E-14',
    'B',
    'manual',
    'replace_right_panel',
    true,
    'przekladniki',
  ),
] as const;

export function getOperationSurfaceByOp(canonicalOp: string): OperationSurfaceEntry | undefined {
  return OPERATION_SURFACE_REGISTRY.find((entry) => entry.canonicalOp === canonicalOp);
}

export function getUnimplementedOperationSurfaces(): OperationSurfaceEntry[] {
  return OPERATION_SURFACE_REGISTRY.filter((entry) => !entry.implemented);
}
