import type { CanonicalOpName } from '../../../types/domainOps';
import type {
  WorkspaceOpenMode,
  WorkspaceScreenCode,
  WorkspaceSurfaceSaveMode,
  WorkspaceSurfaceSizeClass,
} from '../../workspace/types';

export interface OperationSurfaceEntry {
  canonicalOp: CanonicalOpName;
  componentName: string;
  labelPl: string;
  implemented: boolean;
  screenCode: WorkspaceScreenCode;
  sizeClass: WorkspaceSurfaceSizeClass;
  saveMode: WorkspaceSurfaceSaveMode;
  openMode: WorkspaceOpenMode;
  supportsMiniSld: boolean;
  defaultTab: string | null;
}

function entry(
  canonicalOp: CanonicalOpName,
  componentName: string,
  labelPl: string,
  screenCode: WorkspaceScreenCode,
  sizeClass: WorkspaceSurfaceSizeClass,
  saveMode: WorkspaceSurfaceSaveMode,
  openMode: WorkspaceOpenMode,
  supportsMiniSld: boolean,
  defaultTab: string | null,
): OperationSurfaceEntry {
  return {
    canonicalOp,
    componentName,
    labelPl,
    implemented: true,
    screenCode,
    sizeClass,
    saveMode,
    openMode,
    supportsMiniSld,
    defaultTab,
  };
}

export const OPERATION_SURFACE_REGISTRY: readonly OperationSurfaceEntry[] = [
  entry(
    'continue_trunk_segment_sn',
    'KreatorMagistralaSn',
    'Wyprowadź magistralę SN',
    'E-12',
    'C',
    'manual',
    'expand_workspace',
    false,
    'typ',
  ),
  entry(
    'insert_station_on_segment_sn',
    'KreatorStacjiSnNn',
    'Wstaw stację SN/nN',
    'E-13',
    'B',
    'manual',
    'replace_right_panel',
    true,
    'typ-topologiczny',
  ),
  entry(
    'start_branch_segment_sn',
    'StartBranchForm',
    'Dodaj odgałęzienie SN',
    'E-16',
    'A',
    'manual',
    'replace_right_panel',
    false,
    'rodzina-odgalezienia',
  ),
  entry(
    'insert_section_switch_sn',
    'KreatorLacznikaSekcyjnego',
    'Wstaw łącznik sekcyjny',
    'E-17',
    'C',
    'manual',
    'expand_workspace',
    false,
    'aparat',
  ),
  entry(
    'connect_secondary_ring_sn',
    'KreatorPierscienia',
    'Domknij pierścień wtórny',
    'E-17',
    'C',
    'manual',
    'expand_workspace',
    false,
    'domkniecie',
  ),
  entry(
    'set_normal_open_point',
    'KreatorPierscienia',
    'Ustaw punkt normalnie otwarty',
    'E-17',
    'C',
    'manual',
    'expand_workspace',
    false,
    'nop',
  ),
  entry(
    'add_nn_outgoing_field',
    'AddNnOutgoingFieldForm',
    'Dodaj odpływ nN',
    'E-19',
    'A',
    'manual',
    'replace_right_panel',
    false,
    'odplywy',
  ),
  entry(
    'add_nn_load',
    'KreatorOdbioruNn',
    'Dodaj odbiór nN',
    'E-20',
    'C',
    'manual',
    'expand_workspace',
    false,
    'dane',
  ),
  entry(
    'add_shunt_compensator_sn',
    'KreatorKompensatoraSn',
    'Dodaj baterię kondensatorów SN',
    'E-20',
    'C',
    'manual',
    'expand_workspace',
    false,
    'typ',
  ),
  entry(
    'add_surge_arrester_sn',
    'KreatorOgranicznikaSn',
    'Dodaj ogranicznik przepięć SN',
    'E-20',
    'C',
    'manual',
    'expand_workspace',
    false,
    'typ',
  ),
  entry(
    'add_converter_source',
    'KreatorZrodlaOze',
    'Dodaj źródło PV/BESS/FW z katalogu',
    'E-21',
    'B',
    'manual',
    'replace_right_panel',
    true,
    'identyfikacja',
  ),
  entry(
    'add_relay',
    'AddRelayForm',
    'Dodaj zabezpieczenie',
    'E-27',
    'B',
    'manual',
    'replace_right_panel',
    true,
    'zabezpieczenia',
  ),
  entry(
    'assign_catalog_to_element',
    'AssignCatalogForm',
    'Przypisz katalog do elementu',
    'E-38',
    'A',
    'manual',
    'replace_right_panel',
    false,
    'katalogi',
  ),
  entry(
    'update_element_parameters',
    'UpdateElementParametersForm',
    'Zmień parametry elementu',
    'E-03',
    'B',
    'manual',
    'replace_right_panel',
    true,
    'parametry',
  ),
  entry(
    'add_genset_nn',
    'AddDispatchableSourceForm',
    'Dodaj agregat nN',
    'E-21',
    'B',
    'manual',
    'replace_right_panel',
    false,
    'zrodla',
  ),
  entry(
    'add_ups_nn',
    'AddDispatchableSourceForm',
    'Dodaj UPS nN',
    'E-21',
    'B',
    'manual',
    'replace_right_panel',
    false,
    'zrodla',
  ),
  entry(
    'add_grid_source_sn',
    'KreatorZrodloZasilania',
    'Dodaj źródło zasilania GPZ',
    'E-10',
    'C',
    'manual',
    'expand_workspace',
    false,
    'identyfikacja',
  ),
  entry(
    'add_sn_bay',
    'KreatorPolaSn',
    'Dodaj pole SN',
    'E-11',
    'C',
    'manual',
    'expand_workspace',
    false,
    'pole',
  ),
  entry(
    'add_transformer_sn_nn',
    'KreatorTransformatoraSnNn',
    'Dodaj transformator SN/nN',
    'E-18',
    'C',
    'manual',
    'expand_workspace',
    false,
    'szyny',
  ),
  entry(
    'insert_branch_pole_on_segment_sn',
    'InsertBranchPoleForm',
    'Wstaw słup rozgałęźny',
    'E-15',
    'B',
    'manual',
    'replace_right_panel',
    true,
    'identyfikacja',
  ),
  entry(
    'insert_zksn_on_segment_sn',
    'InsertZksnForm',
    'Wstaw złącze kablowe SN',
    'E-14',
    'B',
    'transactional',
    'replace_right_panel',
    true,
    'identyfikacja',
  ),
  entry(
    'add_ct',
    'AddMeasurementForm',
    'Dodaj przekładnik prądowy',
    'E-11',
    'B',
    'manual',
    'replace_right_panel',
    true,
    'przekladniki',
  ),
  entry(
    'add_vt',
    'AddMeasurementForm',
    'Dodaj przekładnik napięciowy',
    'E-11',
    'B',
    'manual',
    'replace_right_panel',
    true,
    'przekladniki',
  ),
] as const;

export function getOperationSurfaceByOp(canonicalOp: string): OperationSurfaceEntry | undefined {
  return OPERATION_SURFACE_REGISTRY.find((entry) => entry.canonicalOp === canonicalOp);
}

export function getUnimplementedOperationSurfaces(): OperationSurfaceEntry[] {
  return OPERATION_SURFACE_REGISTRY.filter((entry) => !entry.implemented);
}
