from __future__ import annotations

from collections import Counter
from typing import Any

from .types import CATALOG_CONTRACT_VERSION, CatalogStatus, CatalogVerificationStatus

SOURCE_REFERENCE = "PN-EN 60099-4 / IEC 60099-4 / referencyjny typoszereg ogranicznikow SN"


def _record(
    *,
    item_id: str,
    name: str,
    manufacturer: str,
    model: str,
    u_m_kv: float,
    mcov_kv: float,
    u_rated_kv: float,
    u_residual_at_10ka_kv: float,
    tov_10s_kv: float,
    energy_class: int,
    energy_absorption_kj_per_kv: float,
    bil_protected_kv: float,
    application: str,
    neutral_system: str,
) -> dict[str, Any]:
    return {
        "id": item_id,
        "name": name,
        "params": {
            "u_m_kv": u_m_kv,
            "mcov_kv": mcov_kv,
            "u_rated_kv": u_rated_kv,
            "u_residual_at_10ka_kv": u_residual_at_10ka_kv,
            "tov_10s_kv": tov_10s_kv,
            "energy_class": energy_class,
            "energy_absorption_kj_per_kv": energy_absorption_kj_per_kv,
            "bil_protected_kv": bil_protected_kv,
            "application": application,
            "neutral_system": neutral_system,
            "manufacturer": manufacturer,
            "model": model,
            "standard": "PN-EN 60099-4",
            "verification_status": CatalogVerificationStatus.REFERENCYJNY.value,
            "catalog_status": CatalogStatus.REFERENCYJNY_V1.value,
            "source_reference": SOURCE_REFERENCE,
            "contract_version": CATALOG_CONTRACT_VERSION,
            "verification_note": (
                "Rekord referencyjny do doboru wstepnego. Dobor wykonawczy wymaga "
                "karty katalogowej producenta i weryfikacji TOV dla ukladu sieci."
            ),
        },
    }


SURGE_ARRESTER_TYPES: list[dict[str, Any]] = [
    _record(
        item_id="arrester-abb-polim-d-12kv-10ka",
        name="ABB POLIM-D 12 kV 10 kA",
        manufacturer="ABB",
        model="POLIM-D",
        u_m_kv=12.0,
        mcov_kv=10.2,
        u_rated_kv=12.0,
        u_residual_at_10ka_kv=38.0,
        tov_10s_kv=14.4,
        energy_class=2,
        energy_absorption_kj_per_kv=4.0,
        bil_protected_kv=75.0,
        application="MV_FEEDER",
        neutral_system="COMPENSATED_OR_RESISTIVE",
    ),
    _record(
        item_id="arrester-abb-polim-d-17p5kv-10ka",
        name="ABB POLIM-D 17.5 kV 10 kA",
        manufacturer="ABB",
        model="POLIM-D",
        u_m_kv=17.5,
        mcov_kv=15.3,
        u_rated_kv=18.0,
        u_residual_at_10ka_kv=56.0,
        tov_10s_kv=21.6,
        energy_class=2,
        energy_absorption_kj_per_kv=4.0,
        bil_protected_kv=95.0,
        application="MV_FEEDER",
        neutral_system="COMPENSATED_OR_RESISTIVE",
    ),
    _record(
        item_id="arrester-abb-polim-d-24kv-10ka",
        name="ABB POLIM-D 24 kV 10 kA",
        manufacturer="ABB",
        model="POLIM-D",
        u_m_kv=24.0,
        mcov_kv=20.4,
        u_rated_kv=24.0,
        u_residual_at_10ka_kv=75.0,
        tov_10s_kv=28.8,
        energy_class=2,
        energy_absorption_kj_per_kv=4.0,
        bil_protected_kv=125.0,
        application="MV_FEEDER",
        neutral_system="COMPENSATED_OR_RESISTIVE",
    ),
    _record(
        item_id="arrester-siemens-3ek7-12kv-10ka",
        name="Siemens 3EK7 12 kV 10 kA",
        manufacturer="Siemens",
        model="3EK7",
        u_m_kv=12.0,
        mcov_kv=10.0,
        u_rated_kv=12.0,
        u_residual_at_10ka_kv=39.0,
        tov_10s_kv=14.0,
        energy_class=2,
        energy_absorption_kj_per_kv=3.8,
        bil_protected_kv=75.0,
        application="MV_FEEDER",
        neutral_system="COMPENSATED_OR_RESISTIVE",
    ),
    _record(
        item_id="arrester-siemens-3ek7-17p5kv-10ka",
        name="Siemens 3EK7 17.5 kV 10 kA",
        manufacturer="Siemens",
        model="3EK7",
        u_m_kv=17.5,
        mcov_kv=15.0,
        u_rated_kv=18.0,
        u_residual_at_10ka_kv=57.0,
        tov_10s_kv=21.0,
        energy_class=2,
        energy_absorption_kj_per_kv=3.8,
        bil_protected_kv=95.0,
        application="MV_FEEDER",
        neutral_system="COMPENSATED_OR_RESISTIVE",
    ),
    _record(
        item_id="arrester-siemens-3ek7-24kv-10ka",
        name="Siemens 3EK7 24 kV 10 kA",
        manufacturer="Siemens",
        model="3EK7",
        u_m_kv=24.0,
        mcov_kv=20.0,
        u_rated_kv=24.0,
        u_residual_at_10ka_kv=76.0,
        tov_10s_kv=28.0,
        energy_class=2,
        energy_absorption_kj_per_kv=3.8,
        bil_protected_kv=125.0,
        application="MV_FEEDER",
        neutral_system="COMPENSATED_OR_RESISTIVE",
    ),
    _record(
        item_id="arrester-eaton-ultrasil-12kv-10ka",
        name="Eaton UltraSIL 12 kV 10 kA",
        manufacturer="Eaton",
        model="UltraSIL",
        u_m_kv=12.0,
        mcov_kv=10.0,
        u_rated_kv=12.0,
        u_residual_at_10ka_kv=40.0,
        tov_10s_kv=14.0,
        energy_class=2,
        energy_absorption_kj_per_kv=3.5,
        bil_protected_kv=75.0,
        application="MV_CABLE_TERMINATION",
        neutral_system="RESISTIVE_OR_EFFECTIVE",
    ),
    _record(
        item_id="arrester-eaton-ultrasil-24kv-10ka",
        name="Eaton UltraSIL 24 kV 10 kA",
        manufacturer="Eaton",
        model="UltraSIL",
        u_m_kv=24.0,
        mcov_kv=20.0,
        u_rated_kv=24.0,
        u_residual_at_10ka_kv=78.0,
        tov_10s_kv=28.0,
        energy_class=2,
        energy_absorption_kj_per_kv=3.5,
        bil_protected_kv=125.0,
        application="MV_CABLE_TERMINATION",
        neutral_system="RESISTIVE_OR_EFFECTIVE",
    ),
    _record(
        item_id="arrester-tridelta-sb24-24kv-10ka",
        name="Tridelta SB24 24 kV 10 kA",
        manufacturer="Tridelta",
        model="SB24",
        u_m_kv=24.0,
        mcov_kv=20.4,
        u_rated_kv=24.0,
        u_residual_at_10ka_kv=74.0,
        tov_10s_kv=29.0,
        energy_class=3,
        energy_absorption_kj_per_kv=5.0,
        bil_protected_kv=125.0,
        application="MV_SUBSTATION",
        neutral_system="COMPENSATED_OR_RESISTIVE",
    ),
    _record(
        item_id="arrester-tridelta-sb36-36kv-10ka",
        name="Tridelta SB36 36 kV 10 kA",
        manufacturer="Tridelta",
        model="SB36",
        u_m_kv=36.0,
        mcov_kv=30.6,
        u_rated_kv=36.0,
        u_residual_at_10ka_kv=112.0,
        tov_10s_kv=43.2,
        energy_class=3,
        energy_absorption_kj_per_kv=5.0,
        bil_protected_kv=170.0,
        application="MV_SUBSTATION",
        neutral_system="COMPENSATED_OR_RESISTIVE",
    ),
    _record(
        item_id="arrester-inael-asa-17p5kv-10ka",
        name="INAEL ASA 17.5 kV 10 kA",
        manufacturer="INAEL",
        model="ASA",
        u_m_kv=17.5,
        mcov_kv=15.3,
        u_rated_kv=18.0,
        u_residual_at_10ka_kv=55.0,
        tov_10s_kv=21.5,
        energy_class=2,
        energy_absorption_kj_per_kv=4.2,
        bil_protected_kv=95.0,
        application="MV_FEEDER",
        neutral_system="COMPENSATED_OR_RESISTIVE",
    ),
    _record(
        item_id="arrester-inael-asa-24kv-10ka",
        name="INAEL ASA 24 kV 10 kA",
        manufacturer="INAEL",
        model="ASA",
        u_m_kv=24.0,
        mcov_kv=20.4,
        u_rated_kv=24.0,
        u_residual_at_10ka_kv=73.0,
        tov_10s_kv=28.8,
        energy_class=2,
        energy_absorption_kj_per_kv=4.2,
        bil_protected_kv=125.0,
        application="MV_FEEDER",
        neutral_system="COMPENSATED_OR_RESISTIVE",
    ),
]


def get_all_surge_arrester_types() -> list[dict[str, Any]]:
    return list(SURGE_ARRESTER_TYPES)


def get_surge_arrester_catalog_statistics() -> dict[str, Any]:
    records = get_all_surge_arrester_types()
    params = [record["params"] for record in records]
    return {
        "liczba_ogranicznikow_ogolem": len(records),
        "napiecia_um_kv": sorted({float(item["u_m_kv"]) for item in params}),
        "producenci": sorted({str(item["manufacturer"]) for item in params}),
        "klasy_energetyczne": sorted({int(item["energy_class"]) for item in params}),
        "statusy_weryfikacji": sorted(Counter(str(item["verification_status"]) for item in params)),
        "statusy_katalogowe": sorted(Counter(str(item["catalog_status"]) for item in params)),
        "contract_version": CATALOG_CONTRACT_VERSION,
    }
