/** Teksty PL nN STUDIO (karta P0.9). Wyłącznie polski język techniczny. */
export const NN_STUDIO_STRINGS = {
  // --- Powłoka / wybór stacji ---
  tytul: 'nN STUDIO',
  celJednymZdaniem: 'Zaprojektuj i sprawdź obwody nN jednej stacji: topologia, odcinki, napięcia, zwarcia, SWZ i dobór zabezpieczeń — w jednym miejscu.',
  wybierzStacje: 'Stacja / rozdzielnica nN',
  wybierzStacjePlaceholder: '— wybierz stację z siecią nN —',
  brakStacjiTytul: 'Brak stacji z siecią nN w modelu',
  brakStacjiOpis: 'nN STUDIO pokazuje obwody nN wybranej stacji SN/nN albo samodzielnej rozdzielnicy nN. '
    + 'Dodaj najpierw transformator SN/nN (kreator stacji) albo pole odpływowe nN, żeby powstała sieć do analizy.',
  ariaZakladki: 'Zakładki nN STUDIO',

  // --- Zakładki ---
  zakladkaTopologia: 'Topologia',
  zakladkaOdcinki: 'Odcinki',
  zakladkaNapiecia: 'Napięcia',
  zakladkaZwarcia: 'Zwarcia',
  zakladkaSwz: 'SWZ',
  zakladkaDobor: 'Dobór',

  // --- TOPOLOGIA ---
  drzewoPusteTytul: 'Sieć nN tej stacji jest jeszcze pusta',
  drzewoPusteOpis: 'Dodaj pierwszy odcinek, rozdzielnicę albo aparat, żeby zacząć budować obwody nN.',
  dodajOdcinek: 'Dodaj odcinek',
  dodajRozdzielnice: 'Dodaj rozdzielnicę',
  dodajAparat: 'Dodaj aparat',
  wskazSzyneNajpierw: 'Zaznacz szynę w drzewie, aby dodać od niej kolejny element.',
  ariaDrzewo: 'Drzewo sieci nN',

  // --- ODCINKI (tabela) ---
  kolId: 'ID',
  kolOd: 'Od',
  kolDo: 'Do',
  kolKabel: 'Kabel',
  kolKabelAkcja: 'Zmień',
  kolPrzekroj: 'Przekrój',
  kolMaterial: 'Materiał',
  kolDlugosc: 'Długość',
  kolNTorow: 'n torów',
  kolUlozenie: 'Ułożenie',
  kolIzKatalogowe: 'Iz katalogowe',
  kolStatus: 'Status',
  statusZamkniety: 'Załączony',
  statusOtwarty: 'Otwarty',
  ulozenieKatalogowe: 'Warunki katalogowe',
  odcinkiPusto: 'Brak odcinków kablowych nN w tej sieci. Dodaj pierwszy odcinek w zakładce TOPOLOGIA.',

  // --- NAPIĘCIA ---
  napieciaTytul: 'Profil napięcia wzdłuż trasy',
  napieciaCelJednymZdaniem: 'Sprawdź spadek napięcia od transformatora do najgorszego (albo wybranego) punktu sieci nN.',
  napieciaBrakRozplywu: 'Brak wyniku rozpływu mocy dla tej stacji.',
  napieciaBrakRozplywuAkcja: 'Uruchom rozpływ mocy w zakładce „Wyniki", żeby zobaczyć profil napięcia tej sieci nN.',
  napieciaWybierzPunkt: 'Punkt docelowy',
  napieciaNajgorszyPunkt: 'Najgorszy punkt nN (automatycznie)',
  napieciaBrakSegmentow: 'Sieć nN tej stacji nie ma jeszcze rozwiązanej trasy w wyniku rozpływu (uruchom rozpływ po dodaniu odcinków).',
  napieciaOsX: 'Odcinek trasy',
  napieciaOsY: 'Napięcie',
  napieciaKolDo: 'Do szyny',
  napieciaKolDeltaU: 'ΔU',
  napieciaKolDeltaUProc: 'ΔU [%]',
  napieciaSumaryczne: 'Suma ΔU na trasie',

  // --- ZWARCIA ---
  zwarciaTytul: 'Prąd zwarcia wzdłuż odpływu',
  zwarciaCelJednymZdaniem: 'Zobacz, jak maleje prąd zwarcia jednofazowego (Ik1) wraz z odległością topologiczną od transformatora.',
  zwarciaWybierzOdplyw: 'Odpływ',
  zwarciaBrakDanych: 'Brak danych pętli zwarcia dla tej stacji.',
  zwarciaNieDotyczy: 'Układ sieci tej stacji nie jest objęty metodą pętli TN (IEC 60364-4-41).',
  zwarciaOsX: 'Punkt odpływu (kolejność od transformatora)',
  zwarciaOsY: 'Prąd zwarcia',
  zwarciaSeriaMin: 'Ik1 min',
  zwarciaSeriaMax: 'Ik1 max',
  zwarciaBrakOdplywow: 'Ta stacja nie ma jeszcze żadnego odpływu nN z policzalną pętlą zwarcia.',

  // --- SWZ ---
  swzTytul: 'SWZ — samoczynne wyłączenie zasilania',
  swzCelJednymZdaniem: 'Sprawdź, czy każdy odpływ nN spełnia warunek samoczynnego wyłączenia (IEC 60364-4-41) w najgorszym punkcie.',
  swzBrakDanych: 'Brak danych do oceny SWZ dla tej stacji.',
  swzNieDotyczy: 'Układ sieci tej stacji nie jest objęty metodą pętli TN.',
  swzKolOdplyw: 'Odpływ',
  swzKolNajgorszyPunkt: 'Najgorszy punkt',
  swzKolWerdykt: 'Werdykt',
  swzKolIk1min: 'Ik1 min',
  swzKolIaWymagane: 'Ia wymagane',
  swzKolMargines: 'Margines',
  swzWerdyktSpelnia: 'Spełnia',
  swzWerdyktNieSpelnia: 'Nie spełnia',
  swzWerdyktNierozstrzygalne: 'Nierozstrzygalne',
  swzBrakAparatu: 'Brak zamodelowanego aparatu zabezpieczającego u początku odpływu — dodaj aparat kreatorem „Aparat nN", żeby ocenić SWZ.',
  swzBrakOdplywow: 'Ta stacja nie ma jeszcze żadnego odpływu nN.',
  swzWykresTytul: 'Margines SWZ per odpływ (Ik1min / Ia)',
  swzWykresOsY: 'Margines (× wymagane)',
  swzProgLinia: 'Próg 1,0',

  // --- DOBÓR ---
  doborTytul: 'Dobór aparatu zabezpieczającego',
  doborCelJednymZdaniem: 'Wskaż punkt obwodu i parametry obliczeniowe — zobacz ranking aparatów spełniających wszystkie cztery kryteria normatywne.',
  doborWybierzPunkt: 'Punkt obwodu (szyna docelowa)',
  doborWybierzPunktPlaceholder: '— wybierz szynę nN —',
  doborIb: 'Prąd obliczeniowy Ib',
  doborIzPrime: 'Obciążalność skorygowana Iz′',
  doborIkMax: 'Prąd zwarciowy Ik″max (opcjonalnie)',
  doborUruchom: 'Policz dobór',
  doborBrakPunktu: 'Wybierz szynę i podaj Ib oraz Iz′, aby uruchomić dobór.',
  doborBladDanych: 'Nie udało się policzyć doboru dla tego punktu.',
  doborKolNazwa: 'Kandydat',
  doborKolIn: 'In',
  doborKolZdolnosc: 'Zdolność wyłączania',
  doborKolKwalifikacja: 'Kwalifikuje się',
  doborRekomendacja: 'Rekomendacja',
  doborBrakRekomendacji: 'Żaden kandydat nie spełnia wszystkich czterech kryteriów.',
  doborWykresTytul: 'Koordynacja doboru (Ib / In / Iz′ / Ik″max)',
  doborWykresOsY: 'Prąd',
  doborTak: 'Tak',
  doborNie: 'Nie',
} as const;
