/**
 * Jedno źródło prawdy dla routingu akcji UI na operacje kanoniczne i akcje niepiszące.
 */

export const CONTEXT_ACTION_TO_OPERATION: Record<string, string> = {
  // Properties / parameter editing
  properties: 'update_element_parameters',
  edit_sk3: 'update_element_parameters',
  edit_voltage: 'update_element_parameters',
  edit_rx: 'update_element_parameters',
  edit_impedance: 'update_element_parameters',
  edit_length: 'update_element_parameters',
  edit_load_power: 'update_element_parameters',
  edit_transformer_ratio: 'update_element_parameters',
  edit_parameters: 'update_element_parameters',
  edit_tap: 'update_element_parameters',
  edit_vector_group: 'update_element_parameters',
  edit_power: 'update_element_parameters',
  edit_reactive: 'update_element_parameters',
  edit_kind: 'update_element_parameters',
  edit_connection: 'update_element_parameters',
  edit_control: 'update_element_parameters',
  edit_limits: 'update_element_parameters',
  edit_disconnect: 'update_element_parameters',
  edit_measurement: 'update_element_parameters',
  edit_capacity: 'update_element_parameters',
  edit_soc: 'update_element_parameters',
  edit_mode: 'update_element_parameters',
  edit_strategy: 'update_element_parameters',
  edit_pf: 'update_element_parameters',
  edit_fuel: 'update_element_parameters',
  edit_backup_time: 'update_element_parameters',
  edit_battery: 'update_element_parameters',
  edit_switch: 'update_element_parameters',
  edit_rating: 'update_element_parameters',
  edit_purpose: 'update_element_parameters',
  edit_accuracy: 'update_element_parameters',
  edit_ratio: 'update_element_parameters',
  edit_settings: 'update_element_parameters',
  edit_curve: 'update_element_parameters',
  edit_type: 'update_element_parameters',
  edit_name: 'update_element_parameters',
  edit_description: 'update_element_parameters',
  edit_label: 'update_element_parameters',
  edit_source_params: 'update_element_parameters',
  edit_segment_length: 'update_element_parameters',
  edit_cycles: 'update_element_parameters',
  edit_chemistry: 'update_element_parameters',
  rename: 'update_element_parameters',
  set_normal_state: 'update_element_parameters',
  set_operating_mode: 'update_element_parameters',
  set_time_profile: 'update_element_parameters',
  set_profile: 'update_element_parameters',
  set_source_mode: 'update_element_parameters',
  change_role: 'update_element_parameters',
  change_kind: 'update_element_parameters',
  edit_configuration: 'update_element_parameters',
  change_switchgear: 'update_element_parameters',
  change_ct: 'update_element_parameters',
  change_vt: 'update_element_parameters',
  edit_protection: 'update_element_parameters',
  edit_automation: 'update_element_parameters',
  edit_source: 'update_element_parameters',
  edit_connection_point: 'update_element_parameters',
  edit_operator_profile: 'update_element_parameters',
  edit_source_profile: 'update_element_parameters',
  edit_qu_profile: 'update_element_parameters',
  edit_cosphi_profile: 'update_element_parameters',
  edit_frt_profile: 'update_element_parameters',
  // Catalog operations
  assign_catalog: 'assign_catalog_to_element',
  assign_tr_catalog: 'assign_catalog_to_element',
  assign_bus_catalog: 'assign_catalog_to_element',
  assign_inverter_catalog: 'assign_catalog_to_element',
  assign_storage_catalog: 'assign_catalog_to_element',
  assign_switch_catalog: 'assign_catalog_to_element',
  assign_cable_catalog: 'assign_catalog_to_element',
  // Topology operations — SN
  continue_trunk_segment_sn: 'continue_trunk_segment_sn',
  start_branch_segment_sn: 'start_branch_segment_sn',
  insert_station_on_segment_sn: 'insert_station_on_segment_sn',
  insert_branch_pole: 'insert_branch_pole_on_segment_sn',
  insert_zksn: 'insert_zksn_on_segment_sn',
  insert_section_switch_sn: 'insert_section_switch_sn',
  connect_ring: 'connect_secondary_ring_sn',
  set_normal_open_point: 'set_normal_open_point',
  set_nop: 'set_normal_open_point',
  derive_cable_section: 'start_branch_segment_sn',
  derive_overhead_section: 'start_branch_segment_sn',
  // Element addition — SN
  add_grid_source_sn: 'add_grid_source_sn',
  add_sn_bay: 'add_sn_bay',
  add_transformer_sn_nn: 'add_transformer_sn_nn',
  // Measurement — CT/VT
  add_ct: 'add_ct',
  add_vt: 'add_vt',
  // Protection
  add_relay: 'add_relay',
  edit_relay_settings: 'add_relay',
  // Element addition — nN
  add_nn_load: 'add_nn_load',
  add_converter_source: 'add_converter_source',
  add_genset_nn: 'add_genset_nn',
  add_ups_nn: 'add_ups_nn',
  add_nn_outgoing_field: 'add_nn_outgoing_field',
  // StudyCase operations
  set_switch_states: 'update_element_parameters',
  set_normal_states: 'update_element_parameters',
  set_source_modes: 'update_element_parameters',
  set_analysis_settings: 'update_element_parameters',
  clone_case: 'update_element_parameters',
  // Validation / readiness
  validate_transformer: 'update_element_parameters',
  check_connection_compliance: 'update_element_parameters',
};

export const NAVIGATION_ACTIONS = new Set([
  'open_inspector',
  'show_results',
  'show_field_results',
  'show_sld_values',
  'show_results_on_sld',
  'show_fault_contribution',
  'show_engineering_justification',
  'show_whitebox',
  'show_readiness',
  'check_readiness',
  'show_tree',
  'show_diagram',
  'show_on_diagram',
  'show_topology',
  'show_secondary_links',
  'show_coordination',
  'show_summary',
  'show_per_element',
  'show_overlay',
  'show_ik',
  'show_ip',
  'show_ith',
  'show_idyn',
  'show_voltages',
  'show_currents',
  'show_powers',
  'show_losses',
  'show_comparison',
  'show_delta_overlay',
  'export_data',
  'export_json',
  'export_report',
  'export_pdf',
  'export_docx',
  'export_results',
  'export_whitebox',
  'add_to_report',
  'add_to_compliance_report',
  'history',
  'fix_issues',
  'check_ring',
  'check_nop',
  'check_selectivity',
  'check_collisions',
  'calc_tcc',
  'validate_selectivity',
  'compare_cases',
  'compare_with',
  'compare_snapshots',
  'open_gpz_fields',
  'reserve_ring',
  'release_ring',
]);

export const TOGGLE_ACTIONS = new Set([
  'toggle_switch',
  'change_switch_state',
  'toggle_service',
  'toggle_enabled',
  'delete',
  'delete_field',
  'delete_source',
  'delete_element',
  'disconnect',
  'disconnect_element',
  'edit_geometry',
  'snap_to_grid',
  'reset_geometry',
  'undo_snapshot',
]);

export function resolveContextActionOperation(actionId: string): string | null {
  return CONTEXT_ACTION_TO_OPERATION[actionId] ?? null;
}

export function isNavigationAction(actionId: string): boolean {
  return NAVIGATION_ACTIONS.has(actionId);
}

export function isToggleAction(actionId: string): boolean {
  return TOGGLE_ACTIONS.has(actionId);
}
