"""Warstwa katalogu producentów rozdzielnic SN (goal §11A).

Eksport publiczny:
- Manufacturer / ManufacturerStatus
- SwitchgearFamily / SwitchgearFamilyStatus
- CompleteMvBayTemplate / BayKind / SourceStatus
- ManufacturerRegistry (5 startowych: ZPUE_WLOSZCZOWA, ELEKTROMETAL, ABB,
  SIEMENS, SCHNEIDER_ELECTRIC — wszyscy `requires_catalog`)
"""

from .canonical_fallback import (
    CANONICAL_FALLBACK_REGISTRY,
    get_canonical_fallback_for_bay_kind,
    list_canonical_fallback_for_manufacturer,
    list_canonical_fallback_templates,
    list_switchgear_solution_templates_for_manufacturer,
)
from .complete_mv_bay_template import (
    BayKind,
    CompleteMvBayTemplate,
    SourceStatus,
)
from .device_instance import (
    ApparatusKind,
    BayDeviceInstanceTemplate,
    ElectricalSide,
    StatusWyposazenia,
)
from .errors import NiezgodnoscKonfiguracjiError
from .factory_configuration import (
    FACTORY_CONFIGURATION_REGISTRY,
    FactoryConfiguration,
    FactoryConfigurationUnit,
    get_factory_configuration,
    list_factory_configurations,
    list_factory_configurations_for_family,
)
from .families import (
    ABB__SAFEPLUS,
    ABB__SAFERING,
    ABB__UNIGEAR_ZS1,
    ABB__UNISEC,
    ELEKTROMETAL__E2ALPHA,
    POTWIERDZONE_STATUSY_RODZINY,
    SCHNEIDER__RM6,
    SCHNEIDER__RM_AIRSET,
    SCHNEIDER__SM6_24,
    SIEMENS__8DJH,
    SIEMENS__NXAIR,
    SWITCHGEAR_FAMILY_REGISTRY,
    ZPUE_WLOSZCZOWA__RELF,
    ZPUE_WLOSZCZOWA__RELF_2S,
    ZPUE_WLOSZCZOWA__ROTOBLOK,
    ZPUE_WLOSZCZOWA__ROTOBLOK_AIR,
    ZPUE_WLOSZCZOWA__ROTOBLOK_VCB,
    ZPUE_WLOSZCZOWA__RXD,
    ZPUE_WLOSZCZOWA__TPM,
    ZPUE_WLOSZCZOWA__TPM_AIR,
    get_switchgear_family,
    list_families_for_manufacturer,
    list_offered_switchgear_families,
    list_switchgear_families,
)
from .family_validation import (
    bay_template_supports_apparatus,
    family_supports_apparatus,
    family_supports_bay_kind,
    family_supports_bay_template,
    family_supports_current,
    family_supports_factory_configuration,
    family_supports_short_circuit,
    family_supports_voltage,
    get_family_or_raise,
    wymagaj_rodziny_oferowanej,
)
from .manufacturer import Manufacturer, ManufacturerStatus
from .port_definition import (
    DirectionHint,
    PortDefinitionTemplate,
    PortKind,
)
from .registry import (
    ABB,
    ELEKTROMETAL,
    MANUFACTURER_REGISTRY,
    SCHNEIDER_ELECTRIC,
    SIEMENS,
    ZPUE_WLOSZCZOWA,
    get_manufacturer,
    list_manufacturers,
    manufacturers_requiring_catalog,
    verified_manufacturers,
)
from .switchgear_family import (
    TOR_KONFIGURACJI_WG_KONSTRUKCJI,
    BusbarSystem,
    ConstructionType,
    InsulationType,
    SwitchgearFamily,
    SwitchgearFamilyStatus,
    TorKonfiguracji,
    tor_konfiguracji_dla_konstrukcji,
)

__all__ = [
    "ABB",
    "ABB__SAFEPLUS",
    "ABB__SAFERING",
    "ABB__UNIGEAR_ZS1",
    "ABB__UNISEC",
    "ApparatusKind",
    "BayDeviceInstanceTemplate",
    "BayKind",
    "BusbarSystem",
    "CANONICAL_FALLBACK_REGISTRY",
    "CompleteMvBayTemplate",
    "ConstructionType",
    "DirectionHint",
    "ELEKTROMETAL",
    "ELEKTROMETAL__E2ALPHA",
    "ElectricalSide",
    "FACTORY_CONFIGURATION_REGISTRY",
    "FactoryConfiguration",
    "FactoryConfigurationUnit",
    "InsulationType",
    "MANUFACTURER_REGISTRY",
    "Manufacturer",
    "ManufacturerStatus",
    "NiezgodnoscKonfiguracjiError",
    "POTWIERDZONE_STATUSY_RODZINY",
    "PortDefinitionTemplate",
    "PortKind",
    "SCHNEIDER_ELECTRIC",
    "SCHNEIDER__RM6",
    "SCHNEIDER__RM_AIRSET",
    "SCHNEIDER__SM6_24",
    "SIEMENS",
    "SIEMENS__8DJH",
    "SIEMENS__NXAIR",
    "SWITCHGEAR_FAMILY_REGISTRY",
    "SourceStatus",
    "StatusWyposazenia",
    "SwitchgearFamily",
    "SwitchgearFamilyStatus",
    "TOR_KONFIGURACJI_WG_KONSTRUKCJI",
    "TorKonfiguracji",
    "ZPUE_WLOSZCZOWA",
    "ZPUE_WLOSZCZOWA__RELF",
    "ZPUE_WLOSZCZOWA__RELF_2S",
    "ZPUE_WLOSZCZOWA__ROTOBLOK",
    "ZPUE_WLOSZCZOWA__ROTOBLOK_AIR",
    "ZPUE_WLOSZCZOWA__ROTOBLOK_VCB",
    "ZPUE_WLOSZCZOWA__RXD",
    "ZPUE_WLOSZCZOWA__TPM",
    "ZPUE_WLOSZCZOWA__TPM_AIR",
    "bay_template_supports_apparatus",
    "family_supports_apparatus",
    "family_supports_bay_kind",
    "family_supports_bay_template",
    "family_supports_current",
    "family_supports_factory_configuration",
    "family_supports_short_circuit",
    "family_supports_voltage",
    "get_canonical_fallback_for_bay_kind",
    "get_factory_configuration",
    "get_family_or_raise",
    "get_manufacturer",
    "get_switchgear_family",
    "list_canonical_fallback_for_manufacturer",
    "list_canonical_fallback_templates",
    "list_factory_configurations",
    "list_factory_configurations_for_family",
    "list_families_for_manufacturer",
    "list_manufacturers",
    "list_offered_switchgear_families",
    "list_switchgear_solution_templates_for_manufacturer",
    "list_switchgear_families",
    "manufacturers_requiring_catalog",
    "tor_konfiguracji_dla_konstrukcji",
    "verified_manufacturers",
    "wymagaj_rodziny_oferowanej",
]
