import type { ElementType } from '../types';

const ELEMENT_TYPE_LABELS_PL: Partial<Record<ElementType, string>> = {
  Bus: 'Szyna',
  LineBranch: 'Odcinek',
  TransformerBranch: 'Transformator',
  Switch: 'Łącznik',
  Source: 'Źródło',
  Load: 'Odbiór',
  Generator: 'Generator',
  Measurement: 'Pomiar',
  ProtectionAssignment: 'Zabezpieczenie',
  Terminal: 'Zacisk',
  PortBranch: 'Port',
  Station: 'Stacja',
  BaySN: 'Pole SN',
  Relay: 'Przekaźnik',
  SecondaryLink: 'Połączenie wtórne',
  NOP: 'Punkt normalnie otwarty',
  BusNN: 'Szyna nN',
  MainBreakerNN: 'Wyłącznik główny nN',
  FeederNN: 'Odpływ nN',
  SegmentNN: 'Odcinek nN',
  LoadNN: 'Odbiór nN',
  SwitchboardNN: 'Rozdzielnica nN',
  SourceFieldNN: 'Pole źródłowe nN',
  PVInverter: 'Falownik PV',
  BESSInverter: 'Falownik BESS',
  EnergyStorage: 'Magazyn energii',
  Genset: 'Agregat prądotwórczy',
  UPS: 'UPS',
  EnergyMeter: 'Licznik energii',
  PowerQualityMeter: 'Miernik jakości energii',
  SurgeArresterNN: 'Ogranicznik przepięć nN',
  Earthing: 'Uziemienie',
  MeasurementNN: 'Przekładnik nN',
  AuxBus: 'Szyna pomocnicza',
  ConnectionPoint: 'Punkt przyłączenia',
  SwitchNN: 'Łącznik nN',
  ProtectionNN: 'Zabezpieczenie nN',
  SourceController: 'Sterownik źródła',
  InternalJunction: 'Węzeł wewnętrzny',
  CableJointNN: 'Złącze kablowe nN',
  FaultCurrentLimiter: 'Ogranicznik prądu zwarciowego',
  FilterCompensator: 'Filtr / kompensator',
  TelecontrolDevice: 'Urządzenie telesterowania',
  BusSectionNN: 'Sekcja szyn nN',
  BusCouplerNN: 'Sprzęgło szyn nN',
  ReserveLink: 'Łącznik rezerwowy nN',
  SourceDisconnect: 'Odłącznik źródła',
  PowerLimit: 'Ograniczenie mocy',
  WorkProfile: 'Profil pracy',
  OperatingMode: 'Tryb pracy',
  ConnectionConstraints: 'Warunki przyłączeniowe',
  MeteringBlock: 'Układ pomiarowo-rozliczeniowy',
  SyncPoint: 'Punkt synchronizacji źródła',
  DescriptiveElement: 'Element opisowy',
};

export function formatPropertyGridElementTypeLabel(elementType: string | null | undefined): string {
  if (!elementType) return '—';
  return ELEMENT_TYPE_LABELS_PL[elementType as ElementType] ?? elementType;
}
